// <auto-generated />
using System;
using ClinicaPilates.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaPilates.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404024434_AddScheduleSlotOverrides")]
    partial class AddScheduleSlotOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaPilates.Api.Models.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduleSlotId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleSlotId");

                    b.ToTable("ClassSessions");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ClassSessionStudent", b =>
                {
                    b.Property<int>("ClassSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipmentUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasMakeupCredit")
                        .HasColumnType("boolean");

                    b.Property<bool>("MakeupCreditUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassSessionId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassSessionStudents");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassesPerWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassesPerWeek = 1,
                            IsActive = true,
                            Name = "1x por semana",
                            Periodicity = "Mensal",
                            Price = 210m
                        },
                        new
                        {
                            Id = 2,
                            ClassesPerWeek = 2,
                            IsActive = true,
                            Name = "2x por semana",
                            Periodicity = "Mensal",
                            Price = 350m
                        },
                        new
                        {
                            Id = 3,
                            ClassesPerWeek = 3,
                            IsActive = true,
                            Name = "3x por semana",
                            Periodicity = "Mensal",
                            Price = 430m
                        },
                        new
                        {
                            Id = 4,
                            ClassesPerWeek = 1,
                            IsActive = true,
                            Name = "1x por semana",
                            Periodicity = "Semestral - Recorrente",
                            Price = 180m
                        },
                        new
                        {
                            Id = 5,
                            ClassesPerWeek = 2,
                            IsActive = true,
                            Name = "2x por semana",
                            Periodicity = "Semestral - Recorrente",
                            Price = 300m
                        },
                        new
                        {
                            Id = 6,
                            ClassesPerWeek = 3,
                            IsActive = true,
                            Name = "3x por semana",
                            Periodicity = "Semestral - Recorrente",
                            Price = 390m
                        },
                        new
                        {
                            Id = 7,
                            ClassesPerWeek = 1,
                            IsActive = true,
                            Name = "1x por semana",
                            Periodicity = "Anual - Recorrente",
                            Price = 170m
                        },
                        new
                        {
                            Id = 8,
                            ClassesPerWeek = 2,
                            IsActive = true,
                            Name = "2x por semana",
                            Periodicity = "Anual - Recorrente",
                            Price = 285m
                        },
                        new
                        {
                            Id = 9,
                            ClassesPerWeek = 3,
                            IsActive = true,
                            Name = "3x por semana",
                            Periodicity = "Anual - Recorrente",
                            Price = 370m
                        });
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ScheduleSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("ScheduleSlots");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ScheduleSlotOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxStudentsOverride")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ScheduleSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleSlotId", "Date")
                        .IsUnique();

                    b.ToTable("ScheduleSlotOverrides");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.StudentPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlanPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReferenceMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "ReferenceMonth", "ReferenceYear")
                        .IsUnique();

                    b.ToTable("StudentPayments");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ClassSession", b =>
                {
                    b.HasOne("ClinicaPilates.Api.Models.ScheduleSlot", "ScheduleSlot")
                        .WithMany("ClassSessions")
                        .HasForeignKey("ScheduleSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleSlot");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ClassSessionStudent", b =>
                {
                    b.HasOne("ClinicaPilates.Api.Models.ClassSession", "ClassSession")
                        .WithMany("ClassSessionStudents")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaPilates.Api.Models.Student", "Student")
                        .WithMany("ClassSessionStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ScheduleSlotOverride", b =>
                {
                    b.HasOne("ClinicaPilates.Api.Models.ScheduleSlot", "ScheduleSlot")
                        .WithMany("Overrides")
                        .HasForeignKey("ScheduleSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleSlot");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.Student", b =>
                {
                    b.HasOne("ClinicaPilates.Api.Models.Plan", "Plan")
                        .WithMany("Students")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.StudentPayment", b =>
                {
                    b.HasOne("ClinicaPilates.Api.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ClassSession", b =>
                {
                    b.Navigation("ClassSessionStudents");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.Plan", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.ScheduleSlot", b =>
                {
                    b.Navigation("ClassSessions");

                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("ClinicaPilates.Api.Models.Student", b =>
                {
                    b.Navigation("ClassSessionStudents");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
